name: release

on:
  release:
    types: [created]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version-file: .java-version
          distribution: oracle
          cache: maven
      - name: package
        run: |
          echo "artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        id: package
      - name: package jar
        run: mvn clean package
      - name: upload artifact
        env:
          TARGET_PACKAGE: ./target/${{ steps.package.outputs.artifactId }}-${{ steps.package.outputs.version }}-jar-with-dependencies.jar
          PACKAGE_NAME: ${{ steps.package.outputs.artifactId }}-${{ steps.package.outputs.version }}.jar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp $TARGET_PACKAGE $PACKAGE_NAME
          gh release upload ${{ github.event.release.tag_name }} $PACKAGE_NAME
