name: release

on:
  release:
    types: [created]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version-file: .java-version
          distribution: oracle
          cache: maven
      - name: version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        id: version
      - name: package jar
        run: mvn clean package
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/ondemand-server-gce-${{ steps.version.outputs.version }}-jar-with-dependencies.jar
          asset_name: ondemand-server-gce-${{ steps.version.outputs.version }}.jar
          asset_content_type: application/java-archiver
        env:
          GITHUB_TOKEN: ${{ github.token }}
